# Server Port
server.port=8080

# PostgreSQL Connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=postgres
spring.datasource.password=Somiya@9373

# Hibernate properties
# create-drop will create the schema on startup and drop it on shutdown (good for dev)
# update will update the schema without dropping data (safer if you want data to persist)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
